# frozen_string_literal: true

# run these tasks like:
# rake ingredients:task_name

namespace :posts do
  desc 'populate gratitude journal'
  task gratitude_2017: :environment do
    puts 'Populating 2017 gratitude journal...'

    user = User.first
    gratitude = user.post_types.find_by(name: 'Gratitude')

    Post.create!([
      { post_type_id: gratitude.id, date: '2017-01-01', description: "We've enjoyed having a relaxing Christmas and New Year holiday season and are appreciating how quiet this city has been. We've had plenty of good food and went to a couple of great parties that we really enjoyed." },
      { post_type_id: gratitude.id, date: '2017-01-04', description: "I just published 2 new downloadable tarot products in my shiny new Esty store!" },
      { post_type_id: gratitude.id, date: '2017-01-04', description: "I just wrote an instructable about how to make one of the tarot products i just produced today — the Poker-to-Tarot deck conversion kit. Huzzah! http://www.instructables.com/id/Convert-Poker-Cards-to-Tarot-Cards" },
      { post_type_id: gratitude.id, date: '2017-01-07', description: "I did some good chucking today. There were some things that I previously loved but no longer served me and were just lurking around. For example, my skinny jeans from Colombia. I loved them, but I haven't worn them in 2 years. It feels good to have them out of my closet and out of my mind." },
      { post_type_id: gratitude.id, date: '2017-01-07', description: "Mike and I ventured into Westbank big-box-store land and had a great time poking around Barnes and Noble. We ended up with a new kitty book (A Street Cat Named Bob) and a connect the dots book. We ended the evening going the the vietnamese restaurant we'd been meaning to get to for the past 6 months —- and it was terrible! Ha ha ha! Fun adventure though." },
      { post_type_id: gratitude.id, date: '2017-01-08', description: "I am enjoying seeing stats of what people like on my Etsy shop. It is nice to have some form of feedback. " },
      { post_type_id: gratitude.id, date: '2017-01-10', description: "I just broke my wordpress site rather heinously. And then I fixed it again. My point is that, though I didn't catch my mistake right away, I know enough about developing in Rails environments to troubleshoot what happened in this completely foreign setup about 10 minutes. That was pretty awesome." },
      { post_type_id: gratitude.id, date: '2017-01-13', description: "After spending all day at the mall, i got to send my mac off to be repaired. Even though my warranty has expired, since I brought my computer in while still under warranty previously, they honored the warranty for me now. Phew! Also, I have a backup computer to use while mine is off being repaired. " },
      { post_type_id: gratitude.id, date: '2017-01-14', description: "I injured my shoulder doing yoga, but it is healing really quickly. I am so glad because it was super painful. I am glad I get a second chance!" },
      { post_type_id: gratitude.id, date: '2017-01-14', description: "Since my computer is off being repaired, I am setting up my ruby/rails env on the media computer. It is really nice to go back to environment set up with some experience — as compared to trying to set it up back when I didn't know anything. " },
      { post_type_id: gratitude.id, date: '2017-01-15', description: "We just spent a lovely afternoon in Abita Springs, walking in the woods and along the trail. The nature smells were wonderful and it was so quiet. It was so nice to be out in nature." },
      { post_type_id: gratitude.id, date: '2017-01-19', description: "Mike bought a new posture tool and it is working miraculously! It is really exciting to see him finding support (that works!) to take care of himself." },
      { post_type_id: gratitude.id, date: '2017-01-20', description: "It just occurred to me to write a note of thanks to Yerdle for having been so awesome. And as it turns out, they're not working with retailers to create used inventory in their stores. How awesome is that? Plus I still wrote them a lovely little love letter and that sure felt nice. " },
      { post_type_id: gratitude.id, date: '2017-01-23', description: "I decided to resurrect my adult coloring book and have been working on the last illustrations needed to finish it. It has been a really fun project and I am enjoying it immensely. I am also excited that I may actually be able to sell a few of them via Amazon. " },
      { post_type_id: gratitude.id, date: '2017-01-25', description: "Mike and I got to go to the science museum in Lafayette. It was only $5 to get in and it was an interesting place to go. The best part was the big touch screen with the interactive solar system. Yowza! Then we got a hotel room in Baton Rouge and Mike had himself some long overdue bath tub time. It felt nice to take care of ourselves that way." },
      { post_type_id: gratitude.id, date: '2017-01-30', description: "I've been having trouble with my laptop all January and it's taken about 3-4 weeks to get it resolved. The good news is that even though it took several trips to the Apple Store (ug!) I got a new logic board, battery, and keyboard under warranty. My warranty had expired, but since I had reported it before it expired, they still honored it. phew!" },
      { post_type_id: gratitude.id, date: '2017-01-30', description: "I just got a nice note from the Dental Lace person saying that her analytics says that some of the sales she's made lately have come from ashiftedperspective.com and thanks for that :) Wow it feels really nice to have a positive impact on the sales of a product that's a more sustainable choice. It feels like making the world a slightly better place and it sure feels like good kharma. " },
      { post_type_id: gratitude.id, date: '2017-02-01', description: "I have enjoyed sharing my coloring book illustrations with friends. It makes me really excited to finish and publish it!" },
      { post_type_id: gratitude.id, date: '2017-02-02', description: "I just made my first Etsy sale! It was a newly-reduced-in-price printable mini tarot deck. It has also inspired me to finish my children's coloring book and make that available for download on Etsy too. Ooooh fun!" },
      { post_type_id: gratitude.id, date: '2017-02-02', description: "I just spent a little time applying to Rails developer jobs. Although some of the job descriptions made me feel like I'll never know enough things, some of them made me feel like this thing is actually possible. It's an interesting process. We'll see what happens!" },
      { post_type_id: gratitude.id, date: '2017-02-04', description: "Back in December, HumanGear contacted me to let me know a post I wrote about Kleen Kanteen and HumanGear's CapCAP compatibility was out of date and that they now do work together. They sent me a new cap to try. So I emailed Kleen Kanteen to see if they'd send me a bottle — and they will. How cool is that?" },
      { post_type_id: gratitude.id, date: '2017-02-12', description: "Finger cots! I've been struggling with self control and picking a lot lately. I started wearing a pair of gloves just to make it easier to cope. Then it occurred to me that finger cots could be a solution. As it turns out, they are like little comfort blankets of relief. Ahhhhhhhh." },
      { post_type_id: gratitude.id, date: '2017-02-12', description: "My coloring book illustrations have been really fun this week. I'm enjoying the process and am really excited about publishing!" },
      { post_type_id: gratitude.id, date: '2017-02-12', description: "I took the month of January off from facebook. This was an excellent decision. It's an emotional hole and time suck. " },
      { post_type_id: gratitude.id, date: '2017-02-16', description: "I held my first group session to get feedback on my coloring book. I was intimidated by asking in NolaDevs#random slack channel for help, but I did and it worked out nicely. I'm working on asking for help or being more assertive at getting out of my own way. So this was a nice way of practicing that." },
      { post_type_id: gratitude.id, date: '2017-02-26', description: "Mardi Gras parades have been really fun this year. Even though it rained and was cold the first night, it was really fun to get back into catching stuff. I enjoyed meeting a traveller today too. He'd recently gotten back from backpacking in several African countries and was really enjoying the spirit in NOLA. Talking with him reminded me of what it felt like to go to strange new places for the first time and how emboldening it was for me. " },
      { post_type_id: gratitude.id, date: '2017-03-08', description: "I've been applying to jobs and hearing nothing back — but I did hear back from the one job I was really interested in. We'll see what happens next! " },
      { post_type_id: gratitude.id, date: '2017-03-05', description: "I am so close to being finished with my coloring book! I just want to do some final proofing and proof of concept on the drawings with one more person, and then I'm ready to upload my files. Whooeee so excited!" },
      { post_type_id: gratitude.id, date: '2017-03-10', description: "The Finley's basement caught on fire yesterday. Bill escaped with a couple of 1st & 2nd degree burns on his hands. Sandra was not there. One of their cats was killed. When I heard this news, I was devastated and it made me realize how much I love them, how grateful I am that they were not killed in this fire, and how much I will miss them when they eventually die. Sandra has been so loving and generous to me for my whole life. I am fortunate to have had her rooting for me and teaching me important skills like generosity, listening, compassion, and forgiveness." },
      { post_type_id: gratitude.id, date: '2017-03-11', description: "Mike and I decided that we will need to relocate so that we can better advance our careers. Once we made that decision, my heart felt full of sadness and gratitude for how much I have loved living in New Orleans. " },
      { post_type_id: gratitude.id, date: '2017-03-12', description: "Went to the St Patrick's Day parade yesterday. Oh man it sure puts the awesomeness of Mardi Gras in perspective. " },
      { post_type_id: gratitude.id, date: '2017-03-19', description: "HOORAY! It's published! After all of the damn drama, I've finally published my adult coloring book! https://www.createspace.com/6890432 I'm really excited to buy copies and share them with friends!" },
      { post_type_id: gratitude.id, date: '2017-03-20', description: "I just heard back again from Jodi of Dental Lace. Her product is doing really well and attributes part of that to the quote I provided for her. I am so glad she cares enough to keep me personally updated because I often fall into a default mindset that anything I've created is just trivial and not to be noticed. I easily forget how doing good work does actually impact people even if I don't personally see the results. I'm grateful that Jodi reminds me of this." },
      { post_type_id: gratitude.id, date: '2017-03-20', description: "Just a quick note to say 'damn those burritos were delish!' It's nice to have taken a recipe and tweaked it enough to have a really nice, new go-to comfort food. Yum!" },
      { post_type_id: gratitude.id, date: '2017-03-20', description: "Hooray! My coloring book is up on Amazon! https://smile.amazon.com/Adventures-Adulting-Adult-Coloring-Book/dp/1544191367" },
      { post_type_id: gratitude.id, date: '2017-03-26', description: "My coloring book has sold 17 copies in its first 6 days. That's pretty cool!" },
      { post_type_id: gratitude.id, date: '2017-03-26', description: "I have an interview for a job in Nashville on Monday. I hadn't been considering Nashville, but now that I have, I think this is pretty exciting. It's really fun to feel excited about a new job and new city. " },
      { post_type_id: gratitude.id, date: '2017-04-02', description: "We just got back of a super relaxing weekend on a bayou in Slidell. Screened in porch and critter sounds everywhere. Canoeing and bike riding. Amazing Thai curry. It was wonderful! So relaxing!" },
      { post_type_id: gratitude.id, date: '2017-04-10', description: "This morning I feel rested and empowered. This is an excellent feeling." },
      { post_type_id: gratitude.id, date: '2017-04-10', description: "I spent the past few days building an app as part of a job application process. I enjoyed the process because I got to practice the things I know, plus learn some new things. I'm so excited to have implemented syntax highlighting! Pretty simple… but it looks cool ;)" },
      { post_type_id: gratitude.id, date: '2017-04-13', description: "Welp, we've got fleas again. I am glad it is a light infestation and that we know what to do about it. We just called an exterminator to handle outside and we've socked up for inside. " },
      { post_type_id: gratitude.id, date: '2017-04-25', description: "On our flight to Phoenix yesterday, I fainted and convulsed. The whole experience was very scary for both Mike and me. I am grateful that it was just motion sickness and not a stroke or something worse. Also, the Houston airport staff, EMTs, and Southwest support people were all very kind and calm. I am grateful for their help. All things could have been much much worse. The experience also made clear to me just how fragile my life together with Mike is. I love him so much and am grateful for our time together. " },
      { post_type_id: gratitude.id, date: '2017-04-28', description: "We just got back from a week at RailsConf in Phoenix and it was one of the most wonderful professional experiences I've had. For the first time, I was in a building full of 2000(?) people who do the same thing I do. We can talk the same language and then talk about other things. I met about 30 people who I really enjoyed talking to. My goal was to make connections and possibly get a job. I've done a great job at making those connections and my next step is following up with the 2.5 job leads that I have. Aside from accomplishing what I set out to do, I also just really enjoyed myself. Also, it helps validate my crappy experience at Collision last year. Yes, I was being talked over and ignored there. It wasn't just in my head. RailsConf felt like home. Awww friends. :)" },
      { post_type_id: gratitude.id, date: '2017-04-30', description: "I'm really glad I don't live in Phoenix. The city has a corporate ballpark feel to it. And it also feels wide open and empty. Where was everybody? And the train to the airport was not an improvement on that feeling." },
      { post_type_id: gratitude.id, date: '2017-05-06', description: "Mike and I switched career paths so that we could work with inspiring people on inspiring projects. This weekend, I got to check out the code base of a project that organizes getting clothing donated to sexual abuse, trauma, sex trafficking victims. This kind of work falls right in line with that goal of doing good work with good people. It's happening!" },
      { post_type_id: gratitude.id, date: '2017-05-10', description: "I have a rails mentor! So far, we've gone through parts of the productmatchr code base and I've enjoyed learning that 1) my code is pretty clean and 2) I get to learn some ways to refactor the parts I've been wanting to refactor but didn't know how. Also, it's a nice ego boost. This is such an amazing experience!" },
      { post_type_id: gratitude.id, date: '2017-05-12', description: "This week, I found myself in the usual mental state in bed, dreading getting out of bed in the mornings. I decided to make a change to this habit, so I created a list of morning mantras. To help me stop the negative talk and start positive talk. Annnnd so far, it's been amazing. One of the things I say to myself is that I have people around me who want to help me succeed. This has completely changed the way I interact with people and has resulted in at least 2 people reaching out to help me grow. This is so very exciting!" },
      { post_type_id: gratitude.id, date: '2017-05-12', description: "I am so grateful that Mike and I decided to get married. I was reflecting on this thought this week and what I appreciate about it most is that the decision moved us into a path of intentional togetherness. It put us in a place where we are aware that we are actively pursuing a life together instead of passively being near each other while life happens — and this makes for a much more fulfilling relationship." },
      { post_type_id: gratitude.id, date: '2017-05-13', description: "This weekend Mike and I celebrated our 10-year anniversary by going out in the French Quarter and Frenchman street and staying in a unique NOLA hotel. We really loved going to see live music and our weird quirky hotel room. A lot of people travel really far to celebrate an anniversary in the FQ. Our travel time was only 30 min :)" },
      { post_type_id: gratitude.id, date: '2017-06-04', description: "I've been really enjoying diving into Sandi Metz's POODR book. It feels great to learn the concepts behind software design and how to strive for best practices. It is also nice to hear that amazing software doesn't come from geniuses. It comes from iteration. Iteration takes time. I'm getting there :)" },
      { post_type_id: gratitude.id, date: '2017-06-04', description: "I am really excited about my upcoming job interview in California. To be a software engineer at a respected company in California feels like I'm achieving something only other people do. I'm really excited to be going down this path. " },
      { post_type_id: gratitude.id, date: '2017-06-12', description: "I've possibly cracked the code on being able to walk myself down from feeling super anxious/stressed and boy does it feel empowering! The keys 1) stop the thought train and 2) physical movement. I need to get my body moving in a serious technical way. Like P90X kenpo moves. That helps me to breathe and shake out the crappy feelings. Then, 3 minutes of power poses leaves me feeling strong. This worked unbelievably well before my job interview." },
      { post_type_id: gratitude.id, date: '2017-06-12', description: "I just completed an all day technical interview in CA! I did end up doing the Monopoly architecture, which I felt well prepared for. The pairing was a ruby code challenge instead of a rails task, so i got tripped up a little in silly initialize stuff that i never use, but i was able to keep my calm and focus on breaking things down into smaller tasks that i could solve more easily. Overall, I feel like I accomplished the things I set out to do: 1) be able to be myself -- take it or leave it and 2) get a decent read on what it would be like to work there." },
      { post_type_id: gratitude.id, date: '2017-06-18', description: "Carla just offered to host a coloring book party with a theme of Adulting. I get to feature my book! This is so kind and generous of her." },
      { post_type_id: gratitude.id, date: '2017-06-22', description: "I made a point of celebrating my birthday this year, even though I couldn't for the past 2 weeks. We went out for dinner and a movie (Wonder Woman). Crazy. It felt nice to say 'hey it's my birthday! yay me!'" },
      { post_type_id: gratitude.id, date: '2017-06-26', description: "I've spent the last week comparing 2 awesome backpacks — both of which i really want but don't crucially need. It is so funny that I'm being so fussy about this decision. This is what privilege will do to you." },
      { post_type_id: gratitude.id, date: '2017-06-26', description: "My parents are off having an Alaskan cruise adventure. I am so glad they are getting out and doing big things like this instead of staying at home wishing they had done things like this. <3" },
      { post_type_id: gratitude.id, date: '2017-07-01', description: "Well, here's a selfish celebration: the neighbor who is violent and abusive is moving out AND some people we know who are interesting and kind are moving in. This is so exciting!" },
      { post_type_id: gratitude.id, date: '2017-07-09', description: "Mike and I have had a peaceful calmness and simple playfulness in our relationship lately and it is very sweet." },
      { post_type_id: gratitude.id, date: '2017-07-10', description: "I've had a block on learning javascript for a while and now that I dove in via Viking Code School and CodeAcademy, I'm getting it! It feels great to be getting over this block and getting my learn on. Yeah!" },
      { post_type_id: gratitude.id, date: '2017-07-11', description: "I hadn't been able to quite understand the point of 'super' in Ruby inheritance until today. I was working through writing code in JS ES5, JS ES6, and Ruby when i realized that I didn't fully understand Ruby. Now finally had context for understanding the purpose of super. Finally! hooray!" },
      { post_type_id: gratitude.id, date: '2017-07-23', description: "Yesterday, Mike and I were in the flash flooding that happened in MidCity at Broad & Orleans. We didn't realize it was going to be so bad when we drove to the Broad Theater. The theater was starting to flood when we arrived. We are so grateful that the movie we wanted to see was sold out and our second choice was 30 min in because if we could have gotten tickets, our car would have been submerged by the time we got back to it. Instead, we left the theater and made our way back to our car, wading through water that was calf- to knee-height and were able to start the car and get to higher ground and home safely. So lucky. So grateful." },
      { post_type_id: gratitude.id, date: '2017-08-06', description: "Another rain doozy again yesterday, and again we skirted out and escaped by the skin of our teeth. I'm particularly glad that we were able to use our previous experience to make good decisions about when/where/how to get to higher ground and home. Sometimes trauma is just trauma. In this case, we got to learn from it and make better choices. http://www.nola.com/weather/index.ssf/2017/08/new_orleans_flooding_what_we_k.html" },
      { post_type_id: gratitude.id, date: '2017-08-06', description: "I am really enjoying the Viking Code School precourse work. I am feeling so much stronger and more confident. I am also appreciating that I am now having satisfying code conversations at hack night. This is a long time in the making. It comes from me realizing that we're all just learning stuff all the time.  " },
      { post_type_id: gratitude.id, date: '2017-08-13', description: "Today is Sandra's birthday. I get to think about how much I love her and appreciate her being in my life. " },
      { post_type_id: gratitude.id, date: '2017-08-13', description: "NOLA's been flooding because the pumps are broken. I am grateful that the mayor fired the S&WB people who lied about pump status — because lying is unacceptable. Obviously, I am also grateful that our neighborhood has not been flooding. I am grateful for that nearly every day — certainly every day it rains." },
      { post_type_id: gratitude.id, date: '2017-08-13', description: "Holy shit news keeps getting worse. Trump's tough talking North Korea with threat of nuclear war. Feminism took another hit when a google engineer made women's negative reaction sound like weakness after calling us biologically inferior (specifically for writing code). It was gross. There were a bunch of polo-clad college boys marching with torches in support of white supremacy. Things got violent. What the fuck? I feel vulnerable more and more these days and at least I have white skin and a decent face. Those are privileges I carry and I'm grateful for them. I am also grateful that I had about 38 years of relatively stable government in my life. Shit's getting crazy now, but at least I knew a time when it wasn't. I know what it can be like." },
      { post_type_id: gratitude.id, date: '2017-08-13', description: "Since we've been having flooding to deal with, we've gotten 3 genuine offers of a home base to evacuate to. It feels really nice to know that even though those places are really far away they've been offered to us by people who care about us." },
      { post_type_id: gratitude.id, date: '2017-08-16', description: "I've been making my own coconut oil & baking soda deodorant and coconut oil body lotion. I really enjoy being able to take simple ingredients and mixing them into useful, clean products for us to use. " },
      { post_type_id: gratitude.id, date: '2017-08-27', description: "Feeling grateful that my vagina scare was handled quickly and that there appears to be nothing wrong. " },
      { post_type_id: gratitude.id, date: '2017-08-27', description: "Feeling grateful that we didn't have to evacuate this weekend for Hurricane Harvey and that we have a little more time before deciding if we will have to evacuate next weekend." },
      { post_type_id: gratitude.id, date: '2017-08-27', description: "Feeling sad that Jacqui and Ben are moving to Colorado — I've really enjoyed knowing Jacqui and I'll miss her a lot. " },
      { post_type_id: gratitude.id, date: '2017-09-03', description: "Last Sunday, after Mike spent 5 hours monitoring and stressing over Harvey, I just decided that we should leave. Right now. And be done with it. So we did. It took us about 2 hours to go from decision to driving away — which for emptying the fridge, rolling up the rugs, prepping the house, etc for the first time, was pretty good. And even though we drove through the summer heat without a/c, we were able to cool ourselves with frozen vegetables purchased at a highway walmart. We found ourselves in a quiet airbnb in Tallahassee where we felt safe. It was so nice to just feel safe. Thankfully, the heaviest rain skipped NOLA, so the city was spared a big disaster." },
      { post_type_id: gratitude.id, date: '2017-09-09', description: "Got to have movie night with neighbors Jarett and Spence. We watched Starsky and Hutch and we all giggled. " },
      { post_type_id: gratitude.id, date: '2017-09-14', description: "My new batch of newly-designed tarot cards has arrived and I spent the evening stamping and heat setting the bags, correcting a url problem :| , and packing the decks for easy fulfillment. It was fun, exciting, and relaxing to do this kind of work. AND 2 of the decks sold instantly. :) Gratifying." },
      { post_type_id: gratitude.id, date: '2017-09-16', description: "Last week was the stress about whether hurricane Irma would hit us or Florida. It hit Florida. We, instead, had amazing weather. It cooled down a little bit and the humidity dropped and we were all out on the front porches celebrating. " },
      { post_type_id: gratitude.id, date: '2017-09-16', description: "We get to do a little kitty sitting for the Beasties today. Hooray! They're super cute and getting so much bigger. " },
      { post_type_id: gratitude.id, date: '2017-09-26', description: "We got to hang out all afternoon on the couch and watch movies with the neighbor kitties napping between our legs. It just filled our furry hearts up and we were in our kitty bliss. " },
      { post_type_id: gratitude.id, date: '2017-10-02', description: "I feel like I'm cruising through the Viking coursework and learning lots of great stuff. I am so grateful to have 2 mentors now. #winning" },
      { post_type_id: gratitude.id, date: '2017-10-05', description: "It seems like just last week(?) maybe the week before when Mike and I were having a Tom Petty listening marathon. Though I started the train with a need to hear 'Honey Bee', I continued it by listening to his newest stuff. Remarkably, the caliber of his songs stays top notch across his whole career. Impressive. Though the news of his recent death made me feel so sad — given my recent listening party — I am so glad that I got to celebrate his life's catalog before hearing that he died. " },
      { post_type_id: gratitude.id, date: '2017-10-10', description: "Every week it seems I get to be grateful that the latest hurricane (Nate) didn't blow my house away or flood my car to death. I hope that we don't have any further hurricanes, but if we do, I hope we continue to escape harm." },
      { post_type_id: gratitude.id, date: '2017-10-15', description: "So much kitty sitting this weekend! We had an epic snuggle fest with the beasties (and Pitch Perfect 2) and then we got to go brush brush brush little Ciro." },
      { post_type_id: gratitude.id, date: '2017-10-15', description: "I really enjoyed walking around Magazine Street last night during Art for Art's Sake. I even bought a pair of earrings, which is something I do very rarely. I am appreciative of all of the normalcy happening right now. I am afraid that war is coming soon and I want to be grateful for these freedoms. " },
      { post_type_id: gratitude.id, date: '2017-11-10', description: "I was able to quickly crank out an app that calculates my Viking curriculum velocity and projects my graduation date. It was a really fun project and I feel like I've learned one heck of a lot in order to be able to crank it out so quickly. " },
      { post_type_id: gratitude.id, date: '2017-11-16', description: "RubyConf was in New Orleans this year! I got to meet new people and I don't even have to travel for it! And even though Mike and I both had a cold, we were still able to attend the conference and have a great time. " },
      { post_type_id: gratitude.id, date: '2018-11-18', description: "Holy crap. I just woke up to 10 orders for tarot cards. Between that and last night's orders, I'm putting 16 orders in a mailbox on my way to RubyConf today." },
      { post_type_id: gratitude.id, date: '2017-11-18', description: "I got to hear Sandi Metz speak and then shook her hand. Wow she's really super. How does a person be so humble and kind?" },
      { post_type_id: gratitude.id, date: '2017-11-22', description: "I just completed 100 orders on Etsy. That's a nice little milestone there. And I'm pretty sure I'm going to run out of stock before my next shipment arrives. :0 #goodproblems" },
      { post_type_id: gratitude.id, date: '2017-11-26', description: "I really appreciate some small improvements I've made lately. The laundry room dry rack is so much nicer than having clothes hanging everywhere and replacing the castors on my desk with ones that actually work is just really satisfying. " },
      { post_type_id: gratitude.id, date: '2017-11-26', description: "Dinner at the Thai place on Prytania was really good last night. Then, I got to hang out with neighbors for a backyard bonfire. A lovely Saturday night. " },
      { post_type_id: gratitude.id, date: '2017-12-01', description: "I just placed my biggest order of tarot cards for etsy yet: qty 50. Ironically(?) none have sold since the new batch arrived! It is interesting to watch my emotional state change around the getting or not getting of sales. It has been a really fun process this year and I'm glad to have had it." },
      { post_type_id: gratitude.id, date: '2017-12-05', description: "I just found out that my code school is going away in the beginning of February. This made me feel really derailed and vulnerable. The good news is, I will still be able to access the coursework for free after Feb 9th, which isn't the same, but it's better than being totally cut loose." },
      { post_type_id: gratitude.id, date: '2017-12-08', description: "This kind of gratitude always feels off… but there is a wildfire that has burned over 300,000 acres outside Carpinteria/Ventura/Santa Barbara and it is still burning. We could be living there right now because of that job interview in April. I am so glad we are not living there." },
      { post_type_id: gratitude.id, date: '2017-12-10', description: "We hung our canvas tree last night. I really enjoy that silly thing. It feels all festive and is so darn simple!" },
      { post_type_id: gratitude.id, date: '2017-12-10', description: "I'm feeling pretty excited about my tarot dice idea. The prototype blanks will be coming soon and I'm excited to try them out!" },
      { post_type_id: gratitude.id, date: '2017-12-10', description: "It's been really quiet in the neighborhood lately. So peaceful. Very nice." },
      { post_type_id: gratitude.id, date: '2017-12-18', description: "   Week of kitties! Thursday we hung out in a Kitten pod at the No Fleas Market Cat Cafe. Then Friday, we went to see the AcroCats cat circus at a small theater in the Marigny. Uh-dor-able. There was burlesque in the theater after the AcroCats and it was just delightful. So playful and accessible — part juggling and dog tricks, part sexydance & disrobing. I really appreciate the weirdly creative social culture here. It's quite liberating. " },
      { post_type_id: gratitude.id, date: '2017-12-21', description: "I got to meet with Andrew today to discuss equity in ProductMatchr. It was really great to have a frank discussion about what seems fair and how to translate that into paperwork for going forward. In the process, I also got to print out the tarot cheat sheets I just created and got to share my tarot dice prototypes with him. It was fun to talk about exciting new things with him. " },
      { post_type_id: gratitude.id, date: '2017-12-24', description: "It has been a really relaxing Christmas weekend. Mike took off Friday, so Thursday night, we went to the light display in City Park. There was a band of high school-aged kids playing Weezer, Led Zeppelin, Ozzy, etc. It was terrible and so much fun! I loved it. Friday, we went to the French Quarter to walk around and go see music. It's always so amazing that we can walk into a club at 6:30pm on a Friday and there is a killer band playing for no cover. I love that about this city. On Saturday, we took a long walk and ended up eating fancy avocado egg toast for brunch." },
      { post_type_id: gratitude.id, date: '2017-12-24', description: "I'm enjoying playing with tarot product ideas. It's a really fun distraction. This is a new way that I play." },
      { post_type_id: gratitude.id, date: '2017-12-26', description: "We enjoyed a mellow Christmas evening over at Carla & BobShaw's house with their neighbor Nathalie. There were great dessert treats and a roaring gas fireplace and a big piney-smelling pine tree. So nice. Also, the company was just right :)" },
      { post_type_id: gratitude.id, date: '2017-12-31', description: "Well, here we are. The last day of the year. I just spent the weekend refactoring my tarot reading app. I upgraded it from Rails 4 to 5 and did a serious overhaul on the database design and logic. It was the first time I touched the readings code since I built it back in 2014 and it was really satisfying to be able to make so many major improvements. It's always nice to stop an look back down the mountain to see how far I've gone. This was a nice view back down to the trailhead." },












































    ])
    puts "Gratitude Posts count: #{gratitude.posts.count} "
    puts 'Done'
  end

end
