# frozen_string_literal: true

# run these tasks like:
# rake ingredients:task_name

namespace :posts do
  desc 'populate gratitude journal'
  task gratitude_2019: :environment do
    puts 'Populating 2019 gratitude journal...'
    # Post.destroy_all

    user = User.first
    gratitude = user.post_types.find_by(name: 'Gratitude')

    Post.create!([
      { post_type_id: gratitude.id, date: '2019-01-05', description: "This morning, I sat in bed and knocked out a bunch of tasks I've been meaning to do. It's been really cold, but today is the first nice day in a while. I am grateful that I got to take care of a bunch of business and then later I get to go be outside in the nice weather :)" },
      { post_type_id: gratitude.id, date: '2019-01-05', description: "This seems a little silly, but I am grateful that I am able to return a big blanket that I purchased. It was $225, but it is too hot for our needs. It was a big purchase and I don't have to live with that consequence. I really appreciate that." },
      { post_type_id: gratitude.id, date: '2019-01-05', description: "My hip is feeling a little better. It's not fixed and I'm not sure when it will be, but the pain is not worse right now and that is good." },
      { post_type_id: gratitude.id, date: '2019-01-06', description: "Today John Larson asked me if I wanted to join his little company to be groomed to become lead developer. I am so flattered that he asked. The whole point of this career change was to be able to 'work on cool projects with people I like doing work I like' and this is that sort of thing. " },
      { post_type_id: gratitude.id, date: '2019-01-10', description: "Today I deployed code into production at my new job (CMM) for the first time. Hooray!" },
      { post_type_id: gratitude.id, date: '2019-01-10', description: "Our new couch arrived on Monday. We decided to donate our poangs to the Salvation Army. I felt a little emotional about it, strangely. These poang chairs symbolized a simple, lightweight, comfortable, fast living room. I am grateful for these chairs' service to us. When we put them out on the porch this morning for pickup, I didn't stop to thank them. I wish I had because I do appreciate their service to us and I hope the next people who use them enjoy them as well. " },
      { post_type_id: gratitude.id, date: '2019-01-13', description: "We just had our first caturday on our new couch. It was imperfect… as Mike had a fever and we both just came back from the dentist. My face was numb. But little neighbokitty Dawson (aka Chester aka WindowRalph) came over and had a nice good pettin sesh on the couch. Mike's heart was so happy. " },
      { post_type_id: gratitude.id, date: '2019-01-13', description: "I am feeling grateful about my current job. It feels like a good place right now. " },
      { post_type_id: gratitude.id, date: '2019-01-13', description: "Today I watched a video that John Larson made. It was disguised as an 'about us' video, but then halfway through, he looked directly in the camera and called out to me to join the team. He's such a sneaky sneaker! It is very flattering to be pursued for my technical, professional, business, and social skills. " },
      { post_type_id: gratitude.id, date: '2019-01-20', description: "I turned down the opportunity to work with John Larson. In theory, this would be living the dream. I was able to do this because every day at work I feel like I'm reaffirming that I'm at a really good company/situation for my career right now. This is a good feeling." },
      { post_type_id: gratitude.id, date: '2019-01-20', description: "Home space upgrades galore this week! Yesterday we went shopping and finally replaced those terribly disappointing towels with some solid WalMart towels. They're soft and nice. And so is the new throw blanket for the sofa — which I snuggled under last night while watching a movie. AND we replaced the printer stand with a much nicer version. It's the same size (so we won't accidentally accumulate more stuff) but it's just nicer (aka, not falling apart). AND Mike got 3 new shirts that look fabulous on him. It's all about respecting the space and ourselves and I love these upgrades." },
      { post_type_id: gratitude.id, date: '2019-01-20', description: "Tomorrow is MLK day. I am so grateful for the sacrifice that he and the people he led made to make progress in this country. What they were doing was so scary and dangerous and necessary. It takes some serious grit and I respect and appreciate it so very much." },
      { post_type_id: gratitude.id, date: '2019-01-25', description: "Last night Erica Lloyd asked me to be the next director of WWC Austin. She said after Erica declined, both she and Sam (the current director) thought of me next :) . This is not ideal timing for me, but good timing for my ego. I had begun to wonder if the lower turnout at Ruby Tuesday was because I started going and my personality it too big for the room. Erica set that voice straight. " },
      { post_type_id: gratitude.id, date: '2019-02-10', description: "I am appreciating that right now, my job situation is good. I have a boss that respect me and I respect him. I'm expected to struggle and learn. He wants me to continue to grow and to communicate what I'm learning along the way. This is awesome. I don't know how long this particular situation will last, so I'd like to be sure to appreciate it. " },
      { post_type_id: gratitude.id, date: '2019-02-10', description: "We just booked a trip to Isla Mujeres to celebrate my 40th birthday. It has been such a long time since we've had a real vacation (2009?). I am feeling so grateful that we're in a place now where we feel stable enough to be able to spend the time and money on a time dedicated to relaxing. I am really excited about this trip." },
      { post_type_id: gratitude.id, date: '2019-02-10', description: "I just solved the problem of adding ingredients to recipe app. Woo hoo! This is a huge step towards being able to move away from pepperplate and into my own app with my own killer views and queries. Yeah!" },
      { post_type_id: gratitude.id, date: '2019-02-12', description: "I just crushed some SQL querying in a contest we were having at work. And it made me realize that there actually are some things that I know that some people on my team don't. MY front end framework skills are not strong, and that's where I've been spending my time lately, so this is a nice shift of perspective on my abilities. Take that imposter syndrome." },
      { post_type_id: gratitude.id, date: '2019-02-18', description: "I made some great progress on my food planning app! We did a little bit of test driving of the app on Sunday and it helped me to understand which features I needed to work on first. Also, it was nice to jump back to a little front-end JS to remind myself how to do these kinds of things. As it turns out, I can, and my feature is pretty neat ;) I like balancing this app project with work so that 1) I'm still building portfolio pieces and 2) I get to keep building my Rails chops on the side." },
      { post_type_id: gratitude.id, date: '2019-03-16', description: "We went out with Erin and Justin again this weekend. Ohmagosh we might be making friends. This is exciting and intimidating to me.  " },
      { post_type_id: gratitude.id, date: '2019-03-18', description: "I finally get to start physical therapy and start using my body again! I am excited about the idea of being able to walk (and maybe even run) again. " },
      { post_type_id: gratitude.id, date: '2019-03-18', description: "Mike got a job offer that doubles his pay. This is what we have been working so hard for. It is really nice to start to see this coming together. " },
      { post_type_id: gratitude.id, date: '2019-03-24', description: "I am feeling grateful that Mike needed an IP lawyer and I could just send him the one I used. It is nice to not have to research this one thing before getting it done. " },
      { post_type_id: gratitude.id, date: '2019-03-23', description: "Getting stuff in order feels nice. We're both tightening up our wardrobes. We're back to getting the back yard in order. We have our jobs in order. I'm getting my hip in better order. This is just really nice. " },
      { post_type_id: gratitude.id, date: '2019-03-24', description: "Today I just knocked out an app to help me track my hip physical therapy. This is the reason I started down this development path in the first place. I wanted to be able to build tools for myself. And now i can. It's awesome." },
      { post_type_id: gratitude.id, date: '2019-03-29', description: "Work update: word on the street is i have been crushing it at work. Apparently I'm 3rd in my vertical and 9th in the company for doing risk-assessment code reviews (quantity of reviews) and have been knocking socks off with my tendency to be proactive and think about the bigger picture." },
      { post_type_id: gratitude.id, date: '2019-03-29', description: "I think I'm in a pretty good team because I see them doing these kinds of things all of the time. It's hard to be Hermoine in a sea of Rons. " },
      { post_type_id: gratitude.id, date: '2019-03-29', description: "I feel pretty good because I was able to do a decent code review yesterday. I was all 'what do you think about moving this query logic [out of the controller and] into a scope?' And 'I see you just replaced a bunch of metaprogramming with explicit code. Is that to make things more clear or because the pattern was broken and it didn't work anymore?'" },
      { post_type_id: gratitude.id, date: '2019-03-29', description: "I brought forth a user experience issue (that's backed by science) about our new 8-digit key code and pushed back on our crappy product owner when he tried to poo-poo it. I have a feeling that I am going to have to get his buy-in. Fortunately, I've already seeded buy-in from 5 people in different roles. Now I'm going to have to ScottMaslarManipulate him into thinking this is a must-have idea and that it is his own." },
      { post_type_id: gratitude.id, date: '2019-03-31', description: "I bought a bathing suit and a couple of dresses in anticipation of our trip to Isla Mujeres in the summer. It's nice to be excited about a trip! It's also nice to readjust my relationship with dresses again. After a conversation with Dharni about feeling like an imposter who's held back from doing things when i wear dresses, Mike reminded me that I used to wear a 'uniform' green dress 24x7 when we were traveling. I realized that it's not dress so much as the comfort & context. So i chucked my 'beloved' betabrand dress because I was never comfortable in it. It feels good to let it go and to try new dresses." },
      { post_type_id: gratitude.id, date: '2019-04-01', description: "I have been really enjoying building out my PT app. I am getting to practice things like good model design AND I get to learn new things like how to play sound files in javascript. Both the PT and the app work together to inspire me to do better on both fronts. " },
      { post_type_id: gratitude.id, date: '2019-04-02', description: "I am making progress with physical therapy. Now I can more or less walk normally without active pain. There is still plenty of work to do. I feel more confident that surgery may not be a foregone conclusion now.  " },
      { post_type_id: gratitude.id, date: '2019-04-05', description: "Mike and I paid Marcia back the rest of her retainer and have put that final obligation from the old days of LF behind us. It feels good to have that chapter closed." },
      { post_type_id: gratitude.id, date: '2019-04-06', description: "Every week, I look over at my 2019 goals and i am excited to see that i am making progress on all of them. It feels good to be moving forward toward things that are important to me." },
      { post_type_id: gratitude.id, date: '2019-04-06', description: "Feeling pretty grateful that the hail and tornadoes have not made it to us yet." },
      { post_type_id: gratitude.id, date: '2019-04-16', description: "I got to show off my physical therapy tracker app at Ruby Tuesday meetup tonight and it wa met with much acclaim. One of the people there wanted to sign up for an account and use it b/c it is a pretty nifty tool. Personally, I'm really excited about the rep counter feature and the reporting feature at the moment." },
      { post_type_id: gratitude.id, date: '2019-04-18', description: "Hey I've made 600 sales in my Etsy shop. Neato!" },
      { post_type_id: gratitude.id, date: '2019-04-27', description: "I got to go out to see a play with Dharini last night. It is nice to be pursued for friendship! I feel so good that I am making progress in making friends." },
      { post_type_id: gratitude.id, date: '2019-04-28', description: "I just got a bonus at work. $2600 ain't bad." },
      { post_type_id: gratitude.id, date: '2019-04-28', description: "We hung out in the back yard last night listening to music and playing bocce. It was nice to do something different. " },
      { post_type_id: gratitude.id, date: '2019-04-28', description: "I have been banging out features left and right on my recipe and PT tracking apps. Damn it feels good to be able to use a thing, want a new feature, build out that feature, and use it. Yeah! Also, it is really confidence-building to be able to build the tools that I want. " },
      { post_type_id: gratitude.id, date: '2019-05-05', description: "I am on call this week. It is stressful. In fact, I even got woken up twice in 24 hours. BUT nothing terrible happened. I have been able to patch some holes in the process and I am feeling good about having left things a little bit better than they were." },
      { post_type_id: gratitude.id, date: '2019-05-12', description: "Yesterday I volunteered at an instructor at RailsBridge in Austin. My partner (Tom from Thoughtbot) and I taught the Level I class which had tech-savvy people with no programming experience. I was intimidated by this level of newness a bit. But I wanted to do this because my RailsBridge experience in Boulder back in 2014 was not good. I wanted to help other folks actually get started without getting caught up in all of the nonsense and I think I actually did that. I feel pretty proud of how many ah-ha moments there were and how energized everybody was at the end of the day. And I'm proud of myself for filling a lot of the holes I had in my own experience. One of my goals this year is to give back to the tech community. I definitely did a big chunk of that yesterday and that feels really good." },
      { post_type_id: gratitude.id, date: '2019-05-12', description: "Today is our 12th wedding anniversary. I am so lucky to have a husband and partner that loves me and takes such good care of me." },
      { post_type_id: gratitude.id, date: '2019-05-14', description: "I just accepted and merged my first PR as an open source project owner. Awww. :smile:" },
      { post_type_id: gratitude.id, date: '2019-05-22', description: "Tonight I held a remote Ruby Tuesday meetup because the in-person one was cancelled. It felt really nice to have the experience and feel empowered enough to make this happen. I am giving back to the community that has supported me and that feels nice. I also had a little pre-session with Erica to help her practice whiteboard interviewing. Yay :)" },
      { post_type_id: gratitude.id, date: '2019-05-24', description: "I just got a bunch of praise feedback from my work as a TA at RailsBridge. Holy smokes that was so nice to hear! (see it in the evernote file on praise)" },
      { post_type_id: gratitude.id, date: '2019-05-24', description: "As of yesterday, I have officially graduated from Physical Therapy. Hooray! I still have some pain and mobility issues, but my therapist and I feel that I may be pain-free within 2 months if I stick with the program at home. That's pretty neato because surgery was a crappy option" },
      { post_type_id: gratitude.id, date: '2019-06-01', description: "This week, we asked our neighbor, Makayla, who is an interior designer, to come over to help us design our space. I am so grateful that we can work with somebody so close. Also, I'd love to be able to help a young woman build her portfolio." },
      { post_type_id: gratitude.id, date: '2019-06-02', description: "At this point, I've gotten 2 PRs from strangers on my therapy tracker app. Yet again, this person missed the mark. It just helps me to realize that 1) I'm pretty good at this and 2) some people really just try stuff they're not good at and I need to stop believing that everyone on github has a zillion years of experience and that those years of experience indicate that they're actually good at what they do. 'Cause, they're not. See point 1." },
      { post_type_id: gratitude.id, date: '2019-06-02', description: "Our neighbors are staying for another year. Phew! They're really nice to have as duplex-mates. " },
      { post_type_id: gratitude.id, date: '2019-06-02', description: "I get to go to Mexico for my birthday. Awww yeahhh! :)" },
      { post_type_id: gratitude.id, date: '2019-06-07', description: "I got a fun little card in the mail today from Sandra. It had 40 dollars cash in it — one for each candle and one to grow on. lol! Aww I have people who love me :)" },
      { post_type_id: gratitude.id, date: '2019-06-08', description: "YesterdayI was told I got a 4.1% raise for good performance. Yay! But that it only applies to 50% of my salary… boooo. So I negotiated for the full 4.1% on 100% of my salary. That is an uncomfortable conversation, but absolutely worth having. I will hear back from management later." },
      { post_type_id: gratitude.id, date: '2019-06-16', description: "I just spent a week at Isla Mujeres. We took an easy vacation because, damnit, we needed a vacation. It was so nice to do nothing. To sleep in. To eat breakfast buffet. To drink mid-day margaritas. We even got to see Sabina, who, as it turns out, is really delightful to spend time with. And we saw all of our favorite pets. Everybody is older. Sabina is so well. Noche is still with us. The dogs are way less loco. We spent a week wearing 'privilege' wristbands. So much good." },
      { post_type_id: gratitude.id, date: '2019-06-19', description: "I participated as competent member of an innovation days team and built a mvp pwa app in a couple of days" },
      { post_type_id: gratitude.id, date: '2019-06-18', description: "I'm feeling good about my ability to help ruby newcomers understand some basics and I got to practice that last night at Ruby Tuesday when a new woman came and we did a rails overview. " },
      { post_type_id: gratitude.id, date: '2019-06-23', description: "We got to go to an air guitar competition last night with Justin & Erin. That was really fun. It feels nice to have friends. " },
      { post_type_id: gratitude.id, date: '2019-06-28', description: "I have been able to work on a rails app at work recently. It feels nice to be in a world that makes sense and to be able to knock out features independently. I was even able to teach Ashton about keyword args in ruby. See? I don't know nothing! This has also illuminated for me that I've been confusing my inability to succeed in this role as an inability to succeed in this position at all. That is a mistake. Also, I've been assigned to my preferred workstream during the re-org. Hopefully things are looking up!" },
      { post_type_id: gratitude.id, date: '2019-06-30', description: "My new desk arrived this week and damn it feels nice to have a grown-up desk that does all of the things I need it to. It's helping me to feel more mature and respectful of myself, my time, and my skills. " },
      { post_type_id: gratitude.id, date: '2019-06-30', description: "Yesterday, Mike and I ordered the first three things on our list for home improvements. It is really exciting to be getting our space looking nicer for us! " },
      { post_type_id: gratitude.id, date: '2019-07-01', description: "We're celebrating the official first year in this house. This has been a good space for us. It's supported us with very little struggle during a dynamic and mentally challenging year. We're grateful for how quiet it is here, how we have no neighbor struggles, how our landlord is responsive but also hands-off, how the property is pretty and calming, and generally that we like it here. " },
      { post_type_id: gratitude.id, date: '2019-07-28', description: "Somehow I have missed being grateful during the whole month of July. Bad job, me! I've been struggling with work and considering very heavily quitting in the near future. My team was disbanded and we were all reassigned. I was really not enjoying the new vibe of my new team. Fortunately, we got to spend a lot of time together during the onsite. I understand these folks a lot better now than I did before and I am glad about that. I may be able to salvage some learning out of this job yet." },
      { post_type_id: gratitude.id, date: '2019-07-28', description: "As luck had it, my mom's cousins were all getting together at the lake the weekend after my week in Cleveland. It was hard to see my dad looking so depressed and distant. But it was also really great to see my mom so connected to her cousins and her favorite place. We've been talking about their moving to Maryland. It would be very hard for them to lose their social connections and that's difficult to rebuild. I am glad this trip gave me that clarity. " },
      { post_type_id: gratitude.id, date: '2019-07-28', description: "I am excited that my parents are enthusiastically looking for a new house that will support them better in their elderly years. They've made some tough calls about what their priorities are and have found a spot they think will be good for them. They've been actively getting rid of stuff in preparation to downsize. It's a lot of work and I am glad to see them doing it willingly. " },
      { post_type_id: gratitude.id, date: '2019-07-29', description: "I made about $1000 in digital Etsy sales so far this year. That's pretty neato :)" },
      { post_type_id: gratitude.id, date: '2019-08-01', description: "I've had the chance to work with TJ, a person who's really good at explaining things, is playful about work itself, is good at pairing generously, and knows a whole lot of domain knowledge. I've been struggling with our team dynamic, so being able to work with him has been reassuring." },
      { post_type_id: gratitude.id, date: '2019-08-02', description: "Today I was doing some excellent pairing. We were working through complicated conditionals when I suggested to break them out into well-named methods and variables. As soon as we did that, the trouble spots revealed themselves. It felt really nice to be able to use my basic simplifying skills to get the work back on track again. Also, my pair made a point to thank me for suggesting this approach. It allowed us to make the first bit of progress we had in the past hour." },
      { post_type_id: gratitude.id, date: '2019-08-03', description: "I'm feeling grateful that the pain in my hip is minimal and manageable. " },
      { post_type_id: gratitude.id, date: '2019-08-03', description: "I feel grateful to have a quiet, comfortable house and that our living room looks pretty. It is nice to start treating myself like a grown up." },
      { post_type_id: gratitude.id, date: '2019-08-03', description: "I am glad that my parents are making a new home for themselves to suit them better. " },
      { post_type_id: gratitude.id, date: '2019-08-05', description: "Today was a good day at work. I was able to understand the problem, explain the situation to others joining in, offer suggestions, understand the code, and write effective code to resolve things. This is the second time I've felt this way ever at CMM. It feels really nice. I am capable, I'm just not always in a situation where I can move about the ecosystem by myself. " },
      { post_type_id: gratitude.id, date: '2019-08-05', description: "We've had 4 fleas in the house in the past 5 days. I am so glad that we've had a solid 8 months of living here after the fleabit before we had any fleas in the house." },
      { post_type_id: gratitude.id, date: '2019-08-08', description: "Had another day where I got to refactor a bunch of code and have some autonomy in my ruby life at cmm. It felt really great. " },
      { post_type_id: gratitude.id, date: '2019-08-26', description: "I'm glad my parents get to break ground on their new house earlier than I had expected. If all goes well, they'll be moving in to their new house in the Spring. :)" },
      { post_type_id: gratitude.id, date: '2019-08-26', description: "I've been knocking out features incrementally for my food planner app. It feels nice to work through these solutions and them try them out. It's good to practice this process. I'm also enjoying learning some new ruby patterns... though more accurately, i'm enjoying playing with some new patterns once i understand them ;)" },
      { post_type_id: gratitude.id, date: '2019-08-26', description: "It's nice to have a 1:1 with a quasi manager and say that I feel good about my ability to do work. I have not been able to do that before. Perhaps more importantly, the Imposter Monster is completely at bay today." },
      { post_type_id: gratitude.id, date: '2019-09-01', description: "We went to a party last night at a friend's house and got to hang out with interesting people. It was fun! It's been a while since we've been able to do that and it feels nice. " },
      { post_type_id: gratitude.id, date: '2019-09-01', description: "It is good to have the day off. Today we will just be chilin' on the couch. I spent the morning sleeping, then the afternoon tinkering with some async javascript. Now i'll crash on the couch and watch movies then order takeout. A day of rest! Ahhhhhhh." },
      { post_type_id: gratitude.id, date: '2019-09-07', description: "Several years ago, I made some audio tracks of yoga sessions. They're 3 different tracks with the same poses in them. The only difference is the hold time between the poses. I had wanted to make these tracks programmatically, but my software skills didn't exist yet and i had no idea how to render sound. A couple of years later, i had some new programming skills in ruby, but rendering sound in a browser was super intimidating plus async javascript was a no go. Today i built that sound-rendering, async function and can now build these yoga playlists in this app i built. This feels amazing. This is a marker of growth and a reminder that i can build whatever i want to." },
      { post_type_id: gratitude.id, date: '2019-09-19', description: "I'm feeling good about some contributions I've been making lately. I wrote a blog post about recognizing our own progress and it was really impactful for a couple of folks. It feels nice to help someone feel better about themselves. Also, I've been working through some code changes at work and finding bugs along the way. I've been able to share these findings with people to help them learn to avoid them. That also feels nice. And Dave Shah just said thanks for our thoughtful conversations. There are times when I feel like I am not contributing to my communities, or that I'm just an asshole and should shut up. It is nice to balance those times with these times when people let me know that they appreciate how i'm showing up for them." },
      { post_type_id: gratitude.id, date: '2019-09-19', description: "I'm looking forward to hanging out with my new team in Ohio next week. :)" },
      { post_type_id: gratitude.id, date: '2019-09-29', description: "I just had an exhausting week with my team. 8 hour work days + 7 hours of recreation. So much time together! But i enjoyed 90% of that time. It was nice to have a cohesive intention of spending time with my people. I got in some good bonding with some of the people I don't work with regularly. I am looking forward to the next trip." },
      { post_type_id: gratitude.id, date: '2019-09-30', description: "Today coworker Joel mentioned that his talks were accepted at an upcoming conference. One of them is about the importance of side projects. It made me stop and take stock. I've built 3 apps on the side in the first 3 quarters of the year. Plus a blog, a repo with ruby design patterns, and maintaining gems and other things in other apps. That's pretty much a full side project-per-quarter. I like that i've been so inspired and productive despite all of the challenges and feelings of worthlessness at work. :bri-punch:" },
      { post_type_id: gratitude.id, date: '2019-09-30', description: "It is really nice to see my mom being happy these days. She's got a lot of stressful stuff going on, but she seems to be in a much better place than she was 5 years ago. The past couple of years have been the first time i can remember seeing her happy." },
      { post_type_id: gratitude.id, date: '2019-10-03', description: "I finally built the little nightstand shelf thing i had been thinking about for a couple of years. It was set up to be a disaster because the person who cut the wood cut it so crooked that the edges don't line up, but i was able to salvage it with corner braces and now it's in place. It was a fun little project and now i have it in place. Pretty cool. " },
      { post_type_id: gratitude.id, date: '2019-10-12', description: "I had a couple of tough conversations at work where I asked for what I needed and had to keep persisting until it was heard. That was hard, and it felt bad while i was doing it, but I am glad I did it. It took courage and I did it. " },
      { post_type_id: gratitude.id, date: '2019-10-12', description: "Mike and i went out for breakfast today to the fancy omelette place across the road. We never go to fancy, stand-in-line breakfast and it was a nice change of pace to do that. The rest of the day feels lazy and that's kind of nice. " },
      { post_type_id: gratitude.id, date: '2019-10-12', description: "This week, I bought a silly christmas tree dress to wear to the company holiday party and I'm feeling excited about it. " },
      { post_type_id: gratitude.id, date: '2019-10-16', description: "I was asked to co-lead the Ruby Tuesday group again. It is flattering to hear that people think I am a valuable contributor to this community and would like me to represent it in a leadership capacity. I think I may do it this time :)" },
      { post_type_id: gratitude.id, date: '2019-10-18', description: "I knocked out some good work on a Freedom Friday project today at work. It felt nice to have some autonomy and think through some of the features I'd like to have — and then knock them out. Today's posts were a user model + devise and a joint table on users&events. I was feeling excited and capable while working on this project and that was the goal!" },
      { post_type_id: gratitude.id, date: '2019-10-19', description: "I just signed a contract to work with Scott on the side and I'm feeling excited about it. It's been a year and 10 days since I signed the last one. How interesting to compare the dates. It feels like a cycle." },
      { post_type_id: gratitude.id, date: '2019-11-10', description: "Last weekend we had a successful visit with Priscilla and Margaret here in Austin. I was looking forward to showing them some spots in the city that i think they'd really like. It was really nice to see my mom outside of the context of home." },
      { post_type_id: gratitude.id, date: '2019-11-10', description: "A position came available at work and one of my coworkers came to me to see if i was interested. This is pretty nice! I'm excited about applying for the position. It was also nice to hear my work mentor say 'um yes, apply for it' because that group of people is really great to work with. " },
      { post_type_id: gratitude.id, date: '2019-11-10', description: "It is satisfying to make some good progress on the conferences app i'm building as a side project at work." },
      { post_type_id: gratitude.id, date: '2019-11-16', description: "I have the opportunity to do contract work for Scott Maslar. It is fun to work with him again." },
      { post_type_id: gratitude.id, date: '2019-11-16', description: "One of the things I wished I had was a job where the company would pay for em to go to a conference. I have that. It feels good to recognize that. Also, it's kind of baller :)" },
      { post_type_id: gratitude.id, date: '2019-11-15', description: "I just interviewed for an internal position (department swap). It was nice to go to an interview that I wasn't really nervous about. I wanted to represent myself well and make sure I had my questions for them answered. The most anxiety came from being on the spot, but the rest was easy. It is nice to be in this position. " },
      { post_type_id: gratitude.id, date: '2019-11-16', description: "Southwest Airlines now sends a text message with your boarding pass on it. No need to download a stupid spyware app. For this I am grateful!" },
      { post_type_id: gratitude.id, date: '2019-11-22', description: "I was just offered a position in the Patient vertical and accepted. Hooray! Congrats to me! My current manager said he'd be glad to keep me forever, but thinks this would be a good opportunity for me. " },
      { post_type_id: gratitude.id, date: '2019-11-23', description: "I am excited to go out with some new friends tonight to murder myster dinner. This will be fun!" },
      { post_type_id: gratitude.id, date: '2019-11-23', description: "I enjoyed sweeping up the leaves on the back patio. It was satisfying to sweep them all up into a big pile and then put them in a bag. There will be more leaves soon, but it felt good to do some light yard work. " },
      { post_type_id: gratitude.id, date: '2019-11-23', description: "I've been busy for the past few weekends and haven't had time to affix my nightstand to my bedframe and now I finally have! Yay! Now I won't have to keep shoving it into place every night. I feels good to have that be more stable. " },
      { post_type_id: gratitude.id, date: '2019-11-23', description: "This morning I needed to add 2 new recipes of ingredients to the shopping list and that was going to be cumbersome. So instead of doing it the tedious way, i just knocked out the code to do that for me. Now we have that feature! Yay! I am grateful that i have the skill to solve these problems for myself." }
    ])
    puts "Gratitude Posts count: #{gratitude.posts.count} "
    puts 'Done'
  end


  desc 'populate gratitude journal'
  task merit_2019: :environment do
    puts 'Populating 2019 merit notes...'

    user = User.first
    merit = user.post_types.find_by(name: 'Merit')
    merit.posts.destroy_all

    Post.create!([
      { post_type_id: merit.id, date: '2019-01-10', description: "organized onboarding team to keep our hipchat room when migrating to slack" },
      { post_type_id: merit.id, date: '2019-01-20', description: "Been to lightning talks" },
      { post_type_id: merit.id, date: '2019-02-10', description: "Taken Lynda training on docker" },
      { post_type_id: merit.id, date: '2019-02-25', description: "Taken splunk training so i can be more competent in understanding out error logging" },
      { post_type_id: merit.id, date: '2019-03-11', description: "Led Pro Web Retro for the first time. woot! That's a challenging big group to move." },
      { post_type_id: merit.id, date: '2019-03-15', description: "Built out a front end to the Code Day API to give candidates a more organized experience" },
      { post_type_id: merit.id, date: '2019-03-20', description: "Taken ownership of slack bot things: spud, pro web retro" },
      { post_type_id: merit.id, date: '2019-04-01', description: "Updated and moved out team's onboarding checklist to confluence so that our new front end person has a more organized onboarding experience also, @ mentioned her in a couple of rooms" },
      { post_type_id: merit.id, date: '2019-04-10', description: "Working on initiative to improve our deployment checklists in the context of confidence" },
      { post_type_id: merit.id, date: '2019-04-16', description: "written 10 Jira cards by this point in time" },
      { post_type_id: merit.id, date: '2019-04-16', description: "spent a little time with account specialist helping her with SQL concepts since the 101 classes weren't helping" },
      { post_type_id: merit.id, date: '2019-04-22', description: "spent a little time getting vasanth up to speed" },
      { post_type_id: merit.id, date: '2019-04-26', description: "got a bonus 🙂" },
      { post_type_id: merit.id, date: '2019-04-29', description: "asked Mike Jean to get with Julianne and do a walk-through of the front end dev experience with apps. then it happened 🙂" },
      { post_type_id: merit.id, date: '2019-04-26', description: "Saw we had a gap in the ability for remote folks to participate in JOel's teamwork meeting and quickly organized tools and communication strategies to close the gap." },
      { post_type_id: merit.id, date: '2019-05-03', description: "While on-call, i discovered some holes in the process, asked some questions, and updated documentation to make it easier for first-timers (or frankly, people who have just been woken up in the middle of the night) to get started. " },
      { post_type_id: merit.id, date: '2019-05-05', description: "Just for the record, I was woken up by pager duty 4 times in the past week. 3 of these were maintenance things that i really couldn't help with at all. No merit here. Just kind of wondering about my role in this." },
      { post_type_id: merit.id, date: '2019-05-13', description: "Happy to see so many folks in the on-call retro today. I’m pretty sure it would not have been so well-attended if I hadn’t hollered about it at retro last week. Also, it was nice to see that setting up a template and practicing with sending pager alerts was really useful to Leslie." },
      { post_type_id: merit.id, date: '2019-05-18', description: "Have jumped into a couple fo refinement meetings to see what that's about and help out where i can" },
      { post_type_id: merit.id, date: '2019-05-20', description: "Last week i taught a couple of folks how to build a slack bot (for the on-call handover meeting). Now there are more people that have this skill." },
      { post_type_id: merit.id, date: '2019-05-21', description: "I stepped into the on-call meeting to make sure the bot was useful, then we made a couple of changes. It is nice to build internal tools that are useful to people." },
      { post_type_id: merit.id, date: '2019-05-21', description: "i jumped into troubleshooting a #pro-web-intake question to help out the folks on call. I had a working VM, so we used my machine and started the troubleshooting process. Also, I suggested moving the call into a public room, and that enabled others to join more easily. " },
      { post_type_id: merit.id, date: '2019-05-23', description: "After the last readme vs wiki debate, I took the lead on making a decision and making progress. Now we have a solid draft of the improved readme and will be able to present it to the team for feedback at the next retro" },
      { post_type_id: merit.id, date: '2019-05-29', description: "I was doing an RMT today and just couldn't approve it without seeing evidence of the risk being mitigated, so I asked for clarificatoin over and over again until  I heard what i needed to. Now I feel confident in the risk assessment for this PR (PRO-3658). It took some courage to keep pushing back, but i did it 🙂" },
      { post_type_id: merit.id, date: '2019-06-06', description: "Though I was out of my skillset on the Aimovig work, I kept things moving by coordinating with others, negotiating deliverables, and organizing work via jira. We were able to deliver baseline needs in time and then created a plan to deliver the rest immediately afterwards. " },
      { post_type_id: merit.id, date: '2019-06-19', description: "I participated as competent member of an innovation days team and built a mvp pwa app in a couple of days" },
      { post_type_id: merit.id, date: '2019-06-24', description: "I was able to finally resolve the `providers` app readme problem. I enlisted the help of 2 other people, then knocked out a bunch of work moving it into the wiki. I gathered enough consensus and then shipped it. now it is a much better place." },
      { post_type_id: merit.id, date: '2019-06-24', description: "i just knocked out an incredibly useful documentation change that added all of the tech stacks to all of the apps listed in the re-org docs. now i (and others) can make more informed decisions about what workstreams they may want to enter" },
      { post_type_id: merit.id, date: '2019-08-29', description: "taught some folks some new things and felt good about being able to do a decent code review", url: "https://git.innova-partners.com/EHR/indicators-api/pull/436" },
      { post_type_id: merit.id, date: '2019-09-17', description: "I was a really good pair in this card: https://git.innova-partners.com/EHR/EpicRxbc-Admin/pull/8/files i researched methods and libraries on the side. i knew my model validation options, i knew the easy way to make an array of strings from a big chunk of copy/paste text. i pushed back on a controller method,but then we decided to go forward. i encouraged the use of tests.", url: "https://git.innova-partners.com/EHR/EpicRxbc-Admin/pull/8/files" },
      { post_type_id: merit.id, date: '2019-09-18', description: "I've been finding a number of bugs (actual and potential) in indicators-api based on a faulty assumption of truthiness in rails. Most of these cases have been solved by adding a 'present?' or 'presence'", url: "https://jira.covermymeds.com/browse/PUP-183" },
      { post_type_id: merit.id, date: '2019-10-01', description: "Had a good thought on a code review about moving logic out of the view and into something testable.", url: "https://git.innova-partners.com/EHR/indicators-admin/pull/23" },
      { post_type_id: merit.id, date: '2019-10-01', description: "Practiced recognizing the need for documentation/admin work and asking others to do it" },
      { post_type_id: merit.id, date: '2019-10-29', description: "I wrote some really good jira tickets that make it easy for other people to pick up work easily https://jira.covermymeds.com/browse/PUP-257, https://jira.covermymeds.com/browse/PUP-260", url: "https://jira.covermymeds.com/browse/PUP-256" },
      { post_type_id: merit.id, date: '2019-11-04', description: "Nick says people now talk about refinement and refinement is better. people are interested in it and care about it. and these are people who don't like meetings. -- that is coming from my influence", given_by: 'Nick Anderson' },
      { post_type_id: merit.id, date: '2019-11-05', description: "I proofed the heck out of this PR for ncpdp codes which will result in cleaner data and a less-confusing user experience. I get the feeling that others would not have paid that much attention", url: "https://git.innova-partners.com/EHR/EpicRxbc-Admin/pull/15" },
      { post_type_id: merit.id, date: '2019-11-11', description: "Did some good mentoring work in getting Anna started on an HTML project. At the end of the day she was feeling super excited about what she accomplished and felt like she had a better handle on how to get started with her final project." },
      { post_type_id: merit.id, date: '2019-11-14', description: "I just spent some time writing up my PDP and progress on my goals. Since it is November, i've already done a ton of work and it made me realize that even though it doesn't feel like it, i'm kicking ass." },
      { post_type_id: merit.id, date: '2019-11-20', description: "I feel so happy to have been able to connect Glenn with Schneems in-person at RubyConf. This will get Glenn a step closer towards being a Rails Contributor. I'm also so energized by having been able to help Ragav be able engage in 'hallway track' conversations and connections at RubyConf. These kinds of things make me feel happy because they're important moments that can launch a person into personal growth and I am so grateful to be able to do that." },
      { post_type_id: merit.id, date: '2019-11-21', description: "Nailed a puppy to the wall for pa-predictor pickle deploy docs that have reduced deploy time from 3 months to 2 days. For the past 2 weeks, we had a dev for another team swap into our team. He did the pickle file deploy this month and said the documentation was very good and made it easier for anyone from outside the team to go through the process. I wrote those docs. That's all me, baby! And I got some tacos and got to pin a pup to the wall for it 🙂" },
      { post_type_id: merit.id, date: '2019-11-24', description: "Lucky me! The question I just solved for myself didn’t have a good answer on stackoverflow. So I got to post an answer.", url: "https://stackoverflow.com/a/59019890/5009528" },
    ])

    puts "Merit Posts count: #{merit.posts.count} "
    puts 'Done'
  end
end
