# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/suggested_questions', type: :request do
  # SuggestedQuestion. As you add validations to SuggestedQuestion, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip('Add a hash of attributes valid for your model')
  }

  let(:invalid_attributes) {
    skip('Add a hash of attributes invalid for your model')
  }

  describe 'GET /index' do
    it 'renders a successful response' do
      SuggestedQuestion.create! valid_attributes
      get suggested_questions_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      suggested_question = SuggestedQuestion.create! valid_attributes
      get suggested_question_url(suggested_question)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_suggested_question_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      suggested_question = SuggestedQuestion.create! valid_attributes
      get edit_suggested_question_url(suggested_question)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new SuggestedQuestion' do
        expect {
          post suggested_questions_url, params: { suggested_question: valid_attributes }
        }.to change(SuggestedQuestion, :count).by(1)
      end

      it 'redirects to the created suggested_question' do
        post suggested_questions_url, params: { suggested_question: valid_attributes }
        expect(response).to redirect_to(suggested_question_url(SuggestedQuestion.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new SuggestedQuestion' do
        expect {
          post suggested_questions_url, params: { suggested_question: invalid_attributes }
        }.to change(SuggestedQuestion, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post suggested_questions_url, params: { suggested_question: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) {
        skip('Add a hash of attributes valid for your model')
      }

      it 'updates the requested suggested_question' do
        suggested_question = SuggestedQuestion.create! valid_attributes
        patch suggested_question_url(suggested_question), params: { suggested_question: new_attributes }
        suggested_question.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the suggested_question' do
        suggested_question = SuggestedQuestion.create! valid_attributes
        patch suggested_question_url(suggested_question), params: { suggested_question: new_attributes }
        suggested_question.reload
        expect(response).to redirect_to(suggested_question_url(suggested_question))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        suggested_question = SuggestedQuestion.create! valid_attributes
        patch suggested_question_url(suggested_question), params: { suggested_question: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested suggested_question' do
      suggested_question = SuggestedQuestion.create! valid_attributes
      expect {
        delete suggested_question_url(suggested_question)
      }.to change(SuggestedQuestion, :count).by(-1)
    end

    it 'redirects to the suggested_questions list' do
      suggested_question = SuggestedQuestion.create! valid_attributes
      delete suggested_question_url(suggested_question)
      expect(response).to redirect_to(suggested_questions_url)
    end
  end
end
