development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: 'redis://redistogo:d44a2befe2f49f296ad366f2605afe9c@tetra.redistogo.com:9572/'
  channel_prefix: blame_game_production
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
